# Generated by Django 5.2.5 on 2025-08-28 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0004_tag_slug_alter_tag_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_ms', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='practice.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practice.question')),
            ],
            options={
                'indexes': [models.Index(fields=['attempt', 'question', 'started_at'], name='practice_at_attempt_649271_idx')],
            },
        ),
    ]
