# Generated by Django 5.2.5 on 2025-08-28 04:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0005_attemptview'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttemptViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_ms', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='attemptview',
            name='practice_at_attempt_649271_idx',
        ),
        migrations.RemoveField(
            model_name='attemptview',
            name='started_at',
        ),
        migrations.AddField(
            model_name='attemptview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attemptview',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='practice.question'),
        ),
        migrations.AlterField(
            model_name='attemptview',
            name='view_ms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AddIndex(
            model_name='attemptview',
            index=models.Index(fields=['attempt'], name='practice_at_attempt_66edd1_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptview',
            index=models.Index(fields=['question'], name='practice_at_questio_929622_idx'),
        ),
        migrations.AddIndex(
            model_name='attemptview',
            index=models.Index(fields=['created_at'], name='practice_at_created_fdd2a9_idx'),
        ),
        migrations.AddField(
            model_name='attemptviewlog',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='practice.attempt'),
        ),
        migrations.AddField(
            model_name='attemptviewlog',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_logs', to='practice.question'),
        ),
        migrations.AddIndex(
            model_name='attemptviewlog',
            index=models.Index(fields=['attempt', 'question', 'created_at'], name='practice_at_attempt_522b87_idx'),
        ),
    ]
